v1.1.0 (#37)
* dded changes to allow MuxCore event logging.

* Set verbose mode for MuxCore moved from MuxLogger to MuxStats.

* Issue 21 fixed, MuxCore is updated to support new methods for updatei… (#22)

* Issue 21 fixed, MuxCore is updated to support new methods for updateing and retreiving the Customre data.

* Updated the jar lib and MuxStatsExoPlayer.java to match the corresponding MuxCore changes on branch with same name

* everted sentry enabled boolean value to MuxBaseExoPlayer class.

* update MuxCore.jar

* Add missing overrides for AnalyticsListener on 2.10.6 (#24)

Current Mux library fails with errors like
```
java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.analytics.AnalyticsListener.onIsPlayingChanged(com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime, boolean)"
```

* MuxBaseExoPlayer class split to two versions 2_96 and later and prior to 2_9_6

* new core lib

* pull in late init code from mux_stats_late_init

* beta.0 build

* make sure to use the plugin version for the version

* bump to v3.1.0 of MuxCore.jar

* make sure to return paused when paused, ended, or init

* tweak when we send PAUSED events to make sure we do not send too many

* v1.0.0 release

Co-authored-by: Tomislav Kordic <32546640+tomkordic@users.noreply.github.com>
Co-authored-by: Ivan Kryak <kryak.iv@gmail.com>