Add missing overrides for AnalyticsListener on 2.10.6
Current Mux library fails with errors like
```
java.lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.analytics.AnalyticsListener.onIsPlayingChanged(com.google.android.exoplayer2.analytics.AnalyticsListener$EventTime, boolean)"
```